#' @title `targets` Execution Backend for Composable Pipelines
#'
#' @description
#' Optional execution backend that runs a [`sw_pipeline()`][sw_pipeline] through
#' the [`targets`](https://docs.ropensci.org/targets/) package. Each
#' [`sw_step()`][sw_step] in the pipeline is translated to a single
#' `targets::tar_target()` so that:
#' \itemize{
#'   \item reruns automatically skip steps whose definitions have not changed,
#'   \item expensive steps can be parallelised through `targets`' built-in
#'     workers,
#'   \item the user does not have to write or maintain a `_targets.R` script
#'     by hand.
#' }
#'
#' Two entry points are provided:
#' \itemize{
#'   \item [`sw_pipeline_run_targets()`] — generate the script and immediately
#'     run it via `targets::tar_make()`, returning the same shape as
#'     [`sw_pipeline_run()`].
#'   \item [`sw_pipeline_to_targets()`] — generate the script and the
#'     supporting RDS files, but do **not** run anything. Useful for
#'     inspection, hand-editing, or driving `targets` yourself.
#' }
#'
#' The classic sequential backend is unchanged and remains the default; the
#' new backend is opt-in via `sw_pipeline_run(..., backend = "targets")`.
#'
#' @section Caveats:
#' \itemize{
#'   \item Step functions and their captured environments must be
#'     `serialize()`-able. Functions exported from R packages (the common
#'     case via `sw_step_*()` constructors) work transparently because their
#'     enclosing environment is the package namespace.
#'   \item Step names are sanitised to valid R symbols via `make.names()`
#'     before being used as `tar_target` names; the original names remain the
#'     keys of the returned `intermediates` list.
#' }
#'
#' @name targets_backend
#' @keywords internal
NULL

# ---------------------------------------------------------------------------
# Internal helper: ensure targets is available
# ---------------------------------------------------------------------------
.check_targets <- function() {
  if (!requireNamespace("targets", quietly = TRUE)) {
    stop(
      "Package 'targets' is required for the targets execution backend.\n",
      "Install it with: install.packages('targets')",
      call. = FALSE
    )
  }
}

# ---------------------------------------------------------------------------
# Internal helper: sanitise step names into unique R symbols
# ---------------------------------------------------------------------------
.sw_targets_sanitise_names <- function(step_names) {
  sanitised <- make.names(step_names, unique = TRUE)
  stats::setNames(sanitised, step_names)
}

# Names the generated script reserves for the input plumbing. A user step
# whose sanitised name lands on one of these would clash with `tar_target()`
# duplicate-name detection, so we reject it up-front with a clear error.
.SW_TARGETS_RESERVED <- c("sw_input", "sw_input_path")

# ---------------------------------------------------------------------------
# Internal helper: write the _targets.R script and supporting RDS files
# ---------------------------------------------------------------------------
.sw_targets_emit_script <- function(pipeline, script, def_dir) {
  step_names <- vapply(pipeline@steps, function(s) s@name, character(1))
  sym_map    <- .sw_targets_sanitise_names(step_names)

  reserved_hits <- step_names[sym_map %in% .SW_TARGETS_RESERVED]
  if (length(reserved_hits) > 0) {
    stop("Step name(s) ",
         paste(shQuote(reserved_hits), collapse = ", "),
         " collide with internal target names (",
         paste(.SW_TARGETS_RESERVED, collapse = ", "),
         "). Please rename these steps.",
         call. = FALSE)
  }

  # Persist input + each step definition as RDS files. We track each via a
  # `format = "file"` target so targets invalidates only the affected
  # downstream steps when a definition changes.
  input_rds <- file.path(def_dir, ".input.rds")

  # Use the unique sanitised symbol as the RDS filename so two step names
  # that collapse to the same `make.names()` form don't collide.
  step_rds <- vapply(step_names, function(nm) {
    file.path(def_dir, paste0(sym_map[[nm]], ".rds"))
  }, character(1))
  names(step_rds) <- step_names

  for (i in seq_along(step_names)) {
    saveRDS(pipeline@steps[[i]], step_rds[[i]])
  }

  # `q()` produces a single-line, valid R string literal (handles
  # backslashes and embedded quotes correctly). `deparse1` is used so that
  # long paths are guaranteed not to be split into multiple character
  # elements. Available since R 4.0.0; SpectraWeaveR depends on R >= 4.1.0.
  q <- function(x) deparse1(x)

  lines <- c(
    "# Auto-generated by SpectraWeaveR::sw_pipeline_to_targets().",
    "# Do not edit by hand: this file is overwritten on every run.",
    "library(targets)",
    "library(SpectraWeaveR)",
    "",
    "list(",
    sprintf("  targets::tar_target(sw_input_path, %s, format = \"file\"),",
            q(normalizePath(input_rds, winslash = "/", mustWork = FALSE))),
    "  targets::tar_target(sw_input, readRDS(sw_input_path)),",
    ""
  )

  prev_sym <- "sw_input"
  n <- length(step_names)
  for (i in seq_len(n)) {
    nm  <- step_names[[i]]
    sym <- sym_map[[nm]]
    def_path <- normalizePath(step_rds[[i]], winslash = "/", mustWork = FALSE)
    is_last <- i == n
    sep <- if (is_last) "" else ","
    lines <- c(
      lines,
      sprintf("  targets::tar_target(%s_def_path, %s, format = \"file\"),",
              sym, q(def_path)),
      sprintf("  targets::tar_target(%s_def, readRDS(%s_def_path)),",
              sym, sym),
      sprintf("  targets::tar_target(%s, SpectraWeaveR::execute_step(%s_def, %s))%s",
              sym, sym, prev_sym, sep),
      ""
    )
    prev_sym <- sym
  }
  lines <- c(lines, ")")

  writeLines(lines, script)

  list(
    script    = normalizePath(script, winslash = "/", mustWork = FALSE),
    input_rds = input_rds,
    step_rds  = step_rds,
    sym_map   = sym_map
  )
}

# ---------------------------------------------------------------------------
# Public: write a _targets.R script for a pipeline (no execution)
# ---------------------------------------------------------------------------

#' Write a `_targets.R` Script for a Composable Pipeline
#'
#' Translates a [`sw_pipeline()`][sw_pipeline] into a `_targets.R` script and
#' the supporting RDS files that the script reads. Nothing is executed; this
#' is purely a side-effect function.
#'
#' Each [`sw_step()`][sw_step] becomes a single `targets::tar_target()` whose
#' body calls [`execute_step()`] on the deserialised step definition. Step
#' definitions are tracked via `format = "file"` targets so that mutating one
#' step's `ARGS` invalidates only that step and its downstream descendants.
#'
#' @param pipeline A [`Pipeline`][sw_pipeline] S7 object.
#' @param input The initial input data threaded into the first step.
#' @param script Path to the `_targets.R` script to write. Default:
#'   `"_targets.R"` in the current working directory.
#' @param store Path to the `targets` data store. The script writes its
#'   per-step RDS definitions into `<store>/.sw_defs/`. Default: `"_targets"`.
#' @param overwrite Logical; if `FALSE` (the default) and `script` already
#'   exists, the function aborts. Set to `TRUE` to allow overwriting.
#'
#' @return Invisibly, a list with `script`, `input_rds`, `step_rds`, and
#'   `sym_map` (the original-to-sanitised step name map).
#'
#' @seealso [`sw_pipeline_run_targets()`] for one-shot generate-and-run.
#' @export
sw_pipeline_to_targets <- function(pipeline, input,
                                   script = "_targets.R",
                                   store = "_targets",
                                   overwrite = FALSE) {
  .check_s7()
  .check_targets()
  pip_cls <- .get_Pipeline_class()
  if (!S7::S7_inherits(pipeline, pip_cls)) {
    stop("'pipeline' must be a Pipeline object.", call. = FALSE)
  }
  if (length(pipeline@steps) == 0) {
    stop("Pipeline '", pipeline@name, "' has no steps to translate.",
         call. = FALSE)
  }
  if (file.exists(script) && !isTRUE(overwrite)) {
    stop("Script '", script, "' already exists. ",
         "Pass overwrite = TRUE to replace it.", call. = FALSE)
  }

  def_dir <- file.path(store, ".sw_defs")
  dir.create(def_dir, showWarnings = FALSE, recursive = TRUE)

  saveRDS(input, file.path(def_dir, ".input.rds"))

  info <- .sw_targets_emit_script(pipeline, script, def_dir)
  invisible(info)
}

# ---------------------------------------------------------------------------
# Public: write the script and run it via tar_make()
# ---------------------------------------------------------------------------

#' Run a Composable Pipeline Through the `targets` Backend
#'
#' Generates a `_targets.R` script for `pipeline` (via
#' [`sw_pipeline_to_targets()`]), executes it with `targets::tar_make()`, and
#' assembles the result into the same shape returned by
#' [`sw_pipeline_run()`].
#'
#' Reruns are incremental: if `store` already contains a previous run for this
#' pipeline, only steps whose serialised definition has changed (and their
#' downstream descendants) are recomputed.
#'
#' @param pipeline A [`Pipeline`][sw_pipeline] S7 object.
#' @param input The initial input data.
#' @param script Path to the `_targets.R` script to (re)write. Default:
#'   `"_targets.R"` in the current working directory.
#' @param store Path to the `targets` data store. Use a stable, persistent
#'   path to benefit from incremental reruns. Default: `"_targets"`.
#' @param trace Logical; if `TRUE`, uses the `"verbose"` `targets` reporter,
#'   otherwise `"silent"`. Default: `TRUE`.
#' @param callr_function Optional override for `targets::tar_make()`'s
#'   `callr_function`. Pass `NULL` to run in the same R process (handy in
#'   tests). Default: `NULL`.
#' @param ... Additional arguments forwarded to `targets::tar_make()`.
#'
#' @return A named list with the same shape as [`sw_pipeline_run()`]:
#'   \describe{
#'     \item{`result`}{The final output from the last step.}
#'     \item{`intermediates`}{Named list of intermediate results, keyed by the
#'       original (un-sanitised) step name.}
#'     \item{`steps_completed`}{Integer count of steps executed.}
#'   }
#'
#' @seealso [`sw_pipeline_to_targets()`], [`sw_pipeline_run()`].
#' @export
sw_pipeline_run_targets <- function(pipeline, input,
                                    script = "_targets.R",
                                    store = "_targets",
                                    trace = TRUE,
                                    callr_function = NULL,
                                    ...) {
  .check_s7()
  .check_targets()
  pip_cls <- .get_Pipeline_class()
  if (!S7::S7_inherits(pipeline, pip_cls)) {
    stop("'pipeline' must be a Pipeline object.", call. = FALSE)
  }

  info <- sw_pipeline_to_targets(
    pipeline = pipeline,
    input    = input,
    script   = script,
    store    = store,
    overwrite = TRUE
  )

  # Normalise store to an absolute path so that callr child processes
  # (which may run in a different working directory) still find it.
  store_abs <- normalizePath(store, winslash = "/", mustWork = FALSE)

  reporter <- if (isTRUE(trace)) "verbose" else "silent"

  tryCatch(
    targets::tar_make(
      script         = info$script,
      store          = store_abs,
      callr_function = callr_function,
      reporter       = reporter,
      ...
    ),
    error = function(e) {
      stop(sprintf("Pipeline '%s' failed under targets backend: %s",
                   pipeline@name, conditionMessage(e)),
           call. = FALSE)
    }
  )

  step_names <- vapply(pipeline@steps, function(s) s@name, character(1))
  sym_map    <- info$sym_map

  intermediates <- list()
  for (nm in step_names) {
    sym <- sym_map[[nm]]
    intermediates[[nm]] <- targets::tar_read_raw(sym, store = store_abs)
  }

  list(
    result          = intermediates[[length(intermediates)]],
    intermediates   = intermediates,
    steps_completed = length(step_names)
  )
}
